name: To test matrix 
on:
  push:

jobs:
  deploy:
     strategy:                #The strategy section defines how multiple job variations (matrix jobs) are executed.
     fail-fast: false #If any one job fails, all other running or queued matrix jobs are cancelled immediately. True: The remaining jobs will continue running if one fail and its by-default.
       max-parallel: 5 #it will run 5 job at a time.
       matrix:
         os: [ubuntu-latest, ubuntu-20.04, windows-latest]
         images: [hello-world, alpine]
         exclude: 
          - images: alpine
            os: windows-latest
         include:
          - images: amd64/alpine
            os: ubuntu-latest
 
     runs-on: ${{matrix.os}}
     steps:
     - name: Echo Docker Details
       run: docker info

     - name: Run Images on ${{matrix.os}}
       run: docker run ${{matrix.images}}
