name: Exploring Variables and Secret
on:
  Push:
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: aditya
  IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build

      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
#or you can do ${{env.CONTAINER_REGISTRY}}/...

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

