name: Exploring Variables and Secret
on:
  push:
  workflow_dispatch:
  
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build

      run: echo docker build -t /$CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
#or you can do ${{env.CONTAINER_REGISTRY}}/...

    - name: Docker Login
      run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} #this secret.doocker_pass is the secret variable that securly store on repo ---> setting ---> Secrets and variables ---> actions

  deploy:
    needs: docker 
    runs-on: ubuntu-latest
    steps:

    - name: Docker Build
      run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

